name: yubikit_flutter
description: Wrapper for YubiKit iOS and Android SDKs
version: 0.0.32
homepage: https://github.com/Producement/yubikit_flutter

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  yubikit_openpgp: ^1.0.18

dev_dependencies:
  test: ^1.19.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.producement.yubikit_flutter
        pluginClass: YubikitFlutterPlugin
      ios:
        pluginClass: YubikitFlutterPlugin
