name: yubikit_flutter
description: Wrapper for YubiKit iOS and Android SDKs
version: 0.0.3
homepage: https://github.com/Producement/yubikit_flutter

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  convert: ^3.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.producement.yubikit_flutter
        pluginClass: YubikitFlutterPlugin
      ios:
        pluginClass: YubikitFlutterPlugin
