name: Flutter
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # Download all Flutter packages
    - name: Download dependencies
      run: flutter pub get

    # Check for any formatting issues in the code.
    - name: check code format
      run: flutter format --set-exit-if-changed .

    # Run Flutter Analyzer
    - name: Run Flutter Analyzer
      run: flutter analyze

    # Run all unit-tests with code coverage
    - name: Run unit tests
      run: flutter test --coverage
